task: abiomed
algo-name: mbpo
reward-penalty-coef: 0.0
seed: 1
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.0
gamma2: 0.0
gamma3: 0.0
epoch: 200
model_path: /public/gormpo/models/rl/abiomed/realnvp
classifier_model_name: /public/gormpo/models/abiomed/realnvp/abiomed_realnvp
