task: abiomed
algo-name: mbpo_kde_ws
reward-penalty-coef: 0.005
seed: 1
data_path: "synthetic_data/SAC_5000eps_stochastic.npz"
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.3
gamma2: 0.8
gamma3: 0.0
epoch: 100
classifier_model_name: checkpoints/kde/trained_kde_5000eps
