_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
actor_lr:
    value: 0.0003
algo_name:
    value: cormpo
alpha:
    value: 0.2
alpha_lr:
    value: 0.0003
auto_alpha:
    value: true
batch_size:
    value: 256
config:
    value: cormpo/config/evaluate/noisy/cormpo.yaml
critic_lr:
    value: 0.0003
data_path_wm:
    value: null
device:
    value: cuda
devid:
    value: 7
dynamics_lr:
    value: 0.001
dynamics_model_dir:
    value: null
epoch:
    value: 600
eval_episodes:
    value: 1000
gamma:
    value: 0.99
gamma1:
    value: 0
gamma2:
    value: 0
gamma3:
    value: 0
log_freq:
    value: 1000
logdir:
    value: log
max_steps:
    value: 6
model_name:
    value: 10min_1hr_all_data
model_path_wm:
    value: null
model_retain_epochs:
    value: 5
n_elites:
    value: 5
n_ensembles:
    value: 7
noise_rate:
    value: 0.8
noise_scale:
    value: 0.2
policy_path:
    value: checkpoints/policy/noisy_synthetic/policy_abiomed.pth
real_ratio:
    value: 0.05
reward_penalty_coef:
    value: 0
rollout_batch_size:
    value: 5000
rollout_freq:
    value: 1000
rollout_length:
    value: 5
seed:
    value: 1
seeds:
    value:
        - 1
        - 2
        - 3
        - 4
        - 5
step_per_epoch:
    value: 1000
target_entropy:
    value: -1
task:
    value: abiomed
tau:
    value: 0.005
