optimization_metric: stability
bandwidth: 1
k_neighbors: 100
temporal_split: False
plot: True
save_model: trained_kde
save_results: results.pkl
data_path: "synthetic_data/SAC_exp_5000eps_stochastic_noise0.80_scale0.20.npz"
env: abiomed
noise_rate: 0.8
noise_scale: 0.2
seed: 1
optimize_percentile: True