task: abiomed
algo-name: mbpo_kde
reward-penalty-coef: 0.005
seed: 1
data_path: "synthetic_data/SAC_exp_5000eps_stochastic_noise0.80_scale0.20.npz"
noise_rate: 0.8
noise_scale: 0.2
gamma1: 0.0
gamma2: 0.0
gamma3: 0.0
epoch: 100
classifier_model_name: checkpoints/kde/trained_kde_nr0.8_ns0.2_5000eps

